### ISSUE TITLE
Anyone using this? Issue using react boilerplate

### ISSUE THREAD

**Issue by eamonpenland** [Lighthouse-io/react-visjs-timeline#2]
Hey! Having an issue that just popped up. Was working fine.
now getting this issue

`ERROR in ./~/vis/dist/vis.css
Module parse failed: /Users/eamonpenland/Desktop/thingtech/dispatch/dispatch/node_modules/vis/dist/vis.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .vis .overlay {
|   position: absolute;
|   top: 0;
 @ ./~/react-visjs-timeline/build/index.js 13:0-27`

Thanks!

**Comment by EstebanFuentealba** [comment]
`npm install vis url-loader style-loader css-loader --save`

and add to webpack.conf.js

```javascript
{ test: /\.css$/,loader: "style-loader!css-loader?importLoaders=1"},
{ test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' }
```

**Comment by jmatsushita** [comment]
In my case I was stuck with a similar error when trying to use webpack to build the server side of a universal app. I had to:
 - Make sure both `node_modules` : `vis` and `react-visjs-timeline` where not in the externals.
 - use `node-style-loader` instead of `style-loader` (which otherwise reported `Error: The style-loader cannot be used in a non-browser environment`).

**Comment by willmcclellan** [comment]
@jmatsushita Thanks for the info, we haven't done much with SSR - if you get chance and don't mind creating a PR to update the readme with the relevant info, that would be great!

**Comment by prabuvenkat** [comment]
When I tried moving my pilot project into our main project, I ran into this same problem, and am unable to resolve this using any of the methods mentioned here. 

The problem seems to be import of the css file directly in [L2](https://github.com/Lighthouse-io/react-visjs-timeline/blob/master/src/index.js#L2) .. wondering if css modules could be a solution.

(this is kind of a dealbreaker for us unless i can get it working somehow soon.. :-( )

**Comment by willmcclellan** [comment]
@prabuvenkat Do you have any info on why it's failing... errors, examples etc? You have to use a css loader if using webpack to ensure the css is correctly included in your code.

Also, the 'deal' in open source software is that people release projects to the community, in goodwill, and then others who use it contribute back by reporting well documented issues and even contributing a fix.  

Although we really appreciate you using one of our open source projects, comments like that are really unhelpful and not in the spirit of OSS

**Comment by t-hughes** [comment]
@prabuvenkat @willmcclellan I ran into this same issue and none of the solutions worked 100%, but they helped point us in the right direction. We had all the css loaders except the url-loader and we were not looking for `.png` so we prepended that into our current webpack.config using webpack-merge. Not sure if that helps at all, but it worked for me!
