### ISSUE TITLE
moveTo method

### ISSUE THREAD

**Issue by andreoman** [Lighthouse-io/react-visjs-timeline#33]
Hello. 
How to move the window such that given time is centered on screen ? 
I mean is it possible to use moveTo or do you have another way to set active some day or time in timeline ?

Thank you.

**Comment by dvx** [comment]
Ran into the same issue. This can be done like so:

1. Make sure your Timeline has a ref whenever you render it: `<Timeline ref="timeline" />`

2. Assuming this is all the same component, access the `$el` element of that ref and call `moveTo(...)`: `this.refs.timeline.$el.moveTo(value);`

**Comment by willmcclellan** [comment]
@andreoman that's an interesting use case, we handle this a bit differently where we keep reference to the start/end values of the timeline (the window you might say) so we don't 'center' on a particular time. I can see a use case for that although it would be good to keep it inline with react's declarative style instead of having to access the `ref` like @dvx suggested. That's a good workaround for now if you only have a center value

**Comment by payitforwardnow** [comment]
if you're using a functional component you have to do it a little differently. 

const timelineRef = useRef(null);
...
 <Timeline
          ref={timelineRef}
...
timelineRef.current.$el.moveTo(date);
